insert into product_items (item_id, category_id, product_name, product_price) values (1, 2, 'Molasses - Fancy', 63.42);
insert into product_items (item_id, category_id, product_name, product_price) values (2, 10, 'Wine - Cotes Du Rhone', 78.69);
insert into product_items (item_id, category_id, product_name, product_price) values (3, 1, 'Wine - Jackson Triggs Okonagan', 45.57);
insert into product_items (item_id, category_id, product_name, product_price) values (4, 6, 'Otomegusa Dashi Konbu', 62.1);
insert into product_items (item_id, category_id, product_name, product_price) values (5, 1, 'Whmis Spray Bottle Graduated', 48.41);
insert into product_items (item_id, category_id, product_name, product_price) values (6, 3, 'Wine - Penfolds Koonuga Hill', 19.5);
insert into product_items (item_id, category_id, product_name, product_price) values (7, 11, 'Scallops - Live In Shell', 50.8);
insert into product_items (item_id, category_id, product_name, product_price) values (8, 7, 'Swiss Chard - Red', 27.44);
insert into product_items (item_id, category_id, product_name, product_price) values (9, 1, 'Knife Plastic - White', 27.24);
insert into product_items (item_id, category_id, product_name, product_price) values (10, 8, 'Sardines', 88.23);
insert into product_items (item_id, category_id, product_name, product_price) values (11, 4, 'Sambuca - Opal Nera', 36.8);
insert into product_items (item_id, category_id, product_name, product_price) values (12, 7, 'Pimento - Canned', 8.34);
insert into product_items (item_id, category_id, product_name, product_price) values (13, 4, 'Muffin Batt - Blueberry Passion', 47.57);
insert into product_items (item_id, category_id, product_name, product_price) values (14, 10, 'Pepper - Pablano', 71.44);
insert into product_items (item_id, category_id, product_name, product_price) values (15, 11, 'Soup Campbells - Italian Wedding', 44.98);
insert into product_items (item_id, category_id, product_name, product_price) values (16, 6, 'Jicama', 60.16);
insert into product_items (item_id, category_id, product_name, product_price) values (17, 8, 'Sambuca - Ramazzotti', 61.4);
insert into product_items (item_id, category_id, product_name, product_price) values (18, 6, 'Wine - Red, Black Opal Shiraz', 6.63);
insert into product_items (item_id, category_id, product_name, product_price) values (19, 8, 'Wine - Red, Antinori Santa', 15.76);
insert into product_items (item_id, category_id, product_name, product_price) values (20, 1, 'Beef - Striploin', 54.52);
insert into product_items (item_id, category_id, product_name, product_price) values (21, 8, 'Squash - Pattypan, Yellow', 9.56);
insert into product_items (item_id, category_id, product_name, product_price) values (22, 13, 'Brandy Cherry - Mcguinness', 32.29);
insert into product_items (item_id, category_id, product_name, product_price) values (23, 3, 'Wine - Jackson Triggs Okonagan', 1.39);
insert into product_items (item_id, category_id, product_name, product_price) values (24, 4, 'Grapes - Red', 63.57);
insert into product_items (item_id, category_id, product_name, product_price) values (25, 5, 'Chocolate Liqueur - Godet White', 96.19);
insert into product_items (item_id, category_id, product_name, product_price) values (26, 15, 'Wine - Valpolicella Masi', 12.75);
insert into product_items (item_id, category_id, product_name, product_price) values (27, 11, 'Tequila - Sauza Silver', 1.81);
insert into product_items (item_id, category_id, product_name, product_price) values (28, 3, 'Nut - Pistachio, Shelled', 47.01);
insert into product_items (item_id, category_id, product_name, product_price) values (29, 8, 'Milk 2% 500 Ml', 90.89);
insert into product_items (item_id, category_id, product_name, product_price) values (30, 10, 'Soup - Campbells Pasta Fagioli', 64.02);
insert into product_items (item_id, category_id, product_name, product_price) values (31, 6, 'Salsify, Organic', 7.05);
insert into product_items (item_id, category_id, product_name, product_price) values (32, 10, 'Soup Campbells', 43.66);
insert into product_items (item_id, category_id, product_name, product_price) values (33, 15, 'Dasheen', 46.6);
insert into product_items (item_id, category_id, product_name, product_price) values (34, 7, 'Chip - Potato Dill Pickle', 85.85);
insert into product_items (item_id, category_id, product_name, product_price) values (35, 14, 'Wine - Zinfandel Rosenblum', 88.71);
insert into product_items (item_id, category_id, product_name, product_price) values (36, 5, 'Mint - Fresh', 13.6);
insert into product_items (item_id, category_id, product_name, product_price) values (37, 5, 'Cheese - Cheddar, Medium', 53.73);
insert into product_items (item_id, category_id, product_name, product_price) values (38, 1, 'Pasta - Cappellini, Dry', 12.32);
insert into product_items (item_id, category_id, product_name, product_price) values (39, 10, 'Lemonade - Kiwi, 591 Ml', 77.36);
insert into product_items (item_id, category_id, product_name, product_price) values (40, 14, 'Bread - Focaccia Quarter', 69.91);
insert into product_items (item_id, category_id, product_name, product_price) values (41, 5, 'Lemonade - Mandarin, 591 Ml', 51.34);
insert into product_items (item_id, category_id, product_name, product_price) values (42, 5, 'Peppercorns - Pink', 6.65);
insert into product_items (item_id, category_id, product_name, product_price) values (43, 7, 'Thermometer Digital', 8.98);
insert into product_items (item_id, category_id, product_name, product_price) values (44, 6, 'Fruit Mix - Light', 29.95);
insert into product_items (item_id, category_id, product_name, product_price) values (45, 9, 'Wine - Sauvignon Blanc', 24.12);
insert into product_items (item_id, category_id, product_name, product_price) values (46, 4, 'Wine - Red, Pelee Island Merlot', 57.74);
insert into product_items (item_id, category_id, product_name, product_price) values (47, 10, 'Vinegar - Rice', 7.17);
insert into product_items (item_id, category_id, product_name, product_price) values (48, 5, 'Nut - Pecan, Pieces', 28.12);
insert into product_items (item_id, category_id, product_name, product_price) values (49, 7, 'Piping - Bags Quizna', 89.48);
insert into product_items (item_id, category_id, product_name, product_price) values (50, 13, 'Ecolab Crystal Fusion', 2.18);
insert into product_items (item_id, category_id, product_name, product_price) values (51, 4, 'Yogurt - Blueberry, 175 Gr', 89.03);
insert into product_items (item_id, category_id, product_name, product_price) values (52, 10, 'Sprite, Diet - 355ml', 7.09);
insert into product_items (item_id, category_id, product_name, product_price) values (53, 1, 'Trueblue - Blueberry Cranberry', 81.67);
insert into product_items (item_id, category_id, product_name, product_price) values (54, 1, 'Shrimp - 16/20, Peeled Deviened', 55.38);
insert into product_items (item_id, category_id, product_name, product_price) values (55, 3, 'Amarula Cream', 81.89);
insert into product_items (item_id, category_id, product_name, product_price) values (56, 8, 'Triple Sec - Mcguinness', 19.02);
insert into product_items (item_id, category_id, product_name, product_price) values (57, 2, 'Pate - Liver', 21.11);
insert into product_items (item_id, category_id, product_name, product_price) values (58, 12, 'Kellogs All Bran Bars', 26.55);
insert into product_items (item_id, category_id, product_name, product_price) values (59, 4, 'Cheese - Cheddar, Mild', 74.93);
insert into product_items (item_id, category_id, product_name, product_price) values (60, 9, 'Graham Cracker Mix', 9.66);
insert into product_items (item_id, category_id, product_name, product_price) values (61, 4, 'Beans - Black Bean, Canned', 48.75);
insert into product_items (item_id, category_id, product_name, product_price) values (62, 9, 'Muffin Orange Individual', 28.62);
insert into product_items (item_id, category_id, product_name, product_price) values (63, 13, 'Mushroom Morel Fresh', 6.59);
insert into product_items (item_id, category_id, product_name, product_price) values (64, 13, 'Octopus', 56.05);
insert into product_items (item_id, category_id, product_name, product_price) values (65, 1, 'Nut - Macadamia', 74.45);
insert into product_items (item_id, category_id, product_name, product_price) values (66, 15, 'Cookie Dough - Double', 34.24);
insert into product_items (item_id, category_id, product_name, product_price) values (67, 4, 'Soup - Campbells, Lentil', 20.71);
insert into product_items (item_id, category_id, product_name, product_price) values (68, 15, 'Gooseberry', 4.54);
insert into product_items (item_id, category_id, product_name, product_price) values (69, 5, 'Leeks - Baby, White', 91.06);
insert into product_items (item_id, category_id, product_name, product_price) values (70, 5, 'Apricots - Halves', 32.47);
insert into product_items (item_id, category_id, product_name, product_price) values (71, 12, 'Wine - Casablanca Valley', 90.31);
insert into product_items (item_id, category_id, product_name, product_price) values (72, 11, 'Wine - Fat Bastard Merlot', 69.83);
insert into product_items (item_id, category_id, product_name, product_price) values (73, 13, 'Cucumber - Pickling Ontario', 74.83);
insert into product_items (item_id, category_id, product_name, product_price) values (74, 2, 'Jolt Cola', 9.06);
insert into product_items (item_id, category_id, product_name, product_price) values (75, 4, 'Kellogs Cereal In A Cup', 23.37);
insert into product_items (item_id, category_id, product_name, product_price) values (76, 15, 'Cabbage Roll', 36.6);
insert into product_items (item_id, category_id, product_name, product_price) values (77, 4, 'Food Colouring - Red', 56.1);
insert into product_items (item_id, category_id, product_name, product_price) values (78, 12, 'Lid - High Heat, Super Clear', 87.08);
insert into product_items (item_id, category_id, product_name, product_price) values (79, 2, 'Sausage - Andouille', 26.87);
insert into product_items (item_id, category_id, product_name, product_price) values (80, 7, 'Milk - 2% 250 Ml', 78.8);
insert into product_items (item_id, category_id, product_name, product_price) values (81, 12, 'Shrimp - Black Tiger 8 - 12', 61.83);
insert into product_items (item_id, category_id, product_name, product_price) values (82, 9, 'Wine - Chateau Aqueria Tavel', 7.86);
insert into product_items (item_id, category_id, product_name, product_price) values (83, 6, 'Spice - Onion Powder Granulated', 18.01);
insert into product_items (item_id, category_id, product_name, product_price) values (84, 10, 'Potatoes - Mini White 3 Oz', 88.76);
insert into product_items (item_id, category_id, product_name, product_price) values (85, 14, 'Appetizer - Chicken Satay', 68.6);
insert into product_items (item_id, category_id, product_name, product_price) values (86, 7, 'Tomatoes - Plum, Canned', 67.91);
insert into product_items (item_id, category_id, product_name, product_price) values (87, 1, 'Cheese Cloth No 100', 95.97);
insert into product_items (item_id, category_id, product_name, product_price) values (88, 8, 'Sobe - Green Tea', 50.39);
insert into product_items (item_id, category_id, product_name, product_price) values (89, 8, 'Chicken - Whole Fryers', 22.49);
insert into product_items (item_id, category_id, product_name, product_price) values (90, 9, 'Lemonade - Natural, 591 Ml', 74.02);
insert into product_items (item_id, category_id, product_name, product_price) values (91, 3, 'Cod - Fillets', 21.9);
insert into product_items (item_id, category_id, product_name, product_price) values (92, 13, 'Cod - Black Whole Fillet', 49.48);
insert into product_items (item_id, category_id, product_name, product_price) values (93, 13, 'Lettuce - Spring Mix', 45.4);
insert into product_items (item_id, category_id, product_name, product_price) values (94, 9, 'Lettuce - Red Leaf', 78.46);
insert into product_items (item_id, category_id, product_name, product_price) values (95, 2, 'Chilli Paste, Hot Sambal Oelek', 65.05);
insert into product_items (item_id, category_id, product_name, product_price) values (96, 5, 'Wanton Wrap', 98.01);
insert into product_items (item_id, category_id, product_name, product_price) values (97, 3, 'Wine - White, Pinot Grigio', 62.73);
insert into product_items (item_id, category_id, product_name, product_price) values (98, 14, 'Venison - Racks Frenched', 92.51);
insert into product_items (item_id, category_id, product_name, product_price) values (99, 3, 'Muffin Chocolate Individual Wrap', 99.45);
insert into product_items (item_id, category_id, product_name, product_price) values (100, 7, 'V8 Splash Strawberry Kiwi', 90.87);
